"""Expands compact authored corpora into Reading & Writing bank items.

The content here is authored, not templated - each entry is a written sentence
or note set with its own key and distractors. What the script removes is the
JSON boilerplate, not the writing: a Words-in-Context item is a one-line tuple
here instead of twenty lines of schema.

Skills covered: Words in Context and Text Structure and Purpose (Craft &
Structure), Transitions and Rhetorical Synthesis (Expression of Ideas).

Usage:
    python -m scripts.generate_rw_content --out data/question_bank/rw_generated.json
"""

import argparse
import json
import random

WIC_STEM = "Which choice completes the text with the most logical and precise word or phrase?"
TRANS_STEM = "Which choice completes the text with the most logical transition?"

# (difficulty, sentence_with_blank, correct, [distractors], rationale)
WORDS_IN_CONTEXT = [
    ("easy", "The instructions were so ______ that even first-time users assembled the shelf without difficulty.",
     "clear", ["technical", "lengthy", "optional"],
     "Assembling it without difficulty indicates instructions that were easy to follow."),
    ("easy", "Rainfall in the region is ______: some years bring flooding, others almost none at all.",
     "erratic", ["abundant", "predictable", "seasonal"],
     "The colon describes wide swings between extremes, which is what 'erratic' names; 'predictable' is its opposite."),
    ("easy", "The mayor's speech was deliberately ______, lasting under four minutes and naming only one policy.",
     "brief", ["rambling", "hostile", "musical"],
     "Under four minutes and one policy describes shortness, which 'brief' names."),
    ("easy", "Because the fossil was so ______, researchers could identify individual feather barbs.",
     "well preserved", ["fragmentary", "common", "distant"],
     "Seeing individual barbs requires exceptional preservation; 'fragmentary' contradicts it."),
    ("easy", "The new alloy is ______ enough to be shaped by hand yet strong enough to bear a load.",
     "pliable", ["brittle", "opaque", "costly"],
     "Being shaped by hand requires flexibility, which 'pliable' names; 'brittle' is the opposite."),
    ("easy", "Critics found the sequel ______, noting that it repeated the original almost scene for scene.",
     "derivative", ["inventive", "concise", "expensive"],
     "Repeating the original scene for scene is the definition of derivative work."),
    ("easy", "The library's collection of maps is ______, spanning six centuries and four continents.",
     "extensive", ["meager", "recent", "fragile"],
     "Six centuries and four continents describes great range, which 'extensive' names."),
    ("easy", "Her argument was ______: each claim followed from the one before it.",
     "coherent", ["disjointed", "brief", "popular"],
     "Claims following from one another is coherence; 'disjointed' is the opposite."),
    ("medium", "The committee's findings were ______ by the very data the committee had commissioned.",
     "undermined", ["confirmed", "published", "requested"],
     "'By the very data it commissioned' sets up an ironic reversal, so the findings were weakened, not supported."),
    ("medium", "Far from being ______, the treaty's language was chosen to leave each signatory room to interpret it.",
     "precise", ["lengthy", "recent", "translated"],
     "'Far from being' contrasts with language leaving room for interpretation, whose opposite is precision."),
    ("medium", "The artist's late work is notably ______, stripping away the ornament that filled her early canvases.",
     "austere", ["cluttered", "colorful", "commercial"],
     "Stripping away ornament produces austerity; 'cluttered' describes what was removed."),
    ("medium", "Although the theory was initially ______, within a decade it appeared in every introductory textbook.",
     "marginal", ["dominant", "elegant", "testable"],
     "'Although' contrasts the later ubiquity with an obscure beginning, which 'marginal' names."),
    ("medium", "The editor's revisions were ______: she changed three commas and left the argument untouched.",
     "cosmetic", ["substantial", "hostile", "delayed"],
     "Changing three commas while leaving the argument alone is surface-level, which 'cosmetic' names."),
    ("medium", "Rather than ______ the conflicting accounts, the historian presents both and explains why they differ.",
     "reconciling", ["recording", "translating", "publishing"],
     "The contrast is with presenting both accounts separately, so the rejected option is forcing them into agreement."),
    ("medium", "The device's appeal is its ______: it performs one task, and requires no instructions to operate.",
     "simplicity", ["versatility", "durability", "novelty"],
     "One task and no instructions describes simplicity; 'versatility' would mean many tasks."),
    ("medium", "The prosecution's case rested on ______ evidence, since no witness had seen the act itself.",
     "circumstantial", ["direct", "forged", "abundant"],
     "Evidence in the absence of an eyewitness to the act is circumstantial, the opposite of direct."),
    ("medium", "The novel's structure is ______, moving between three centuries without signalling the shifts.",
     "elliptical", ["chronological", "repetitive", "conventional"],
     "Unsignalled jumps across centuries leave gaps for the reader to bridge, which 'elliptical' names."),
    ("hard", "The study's conclusions are ______ by its sample, which was drawn entirely from one hospital.",
     "circumscribed", ["corroborated", "popularized", "duplicated"],
     "A sample from a single hospital limits how far conclusions extend; 'circumscribed' names that limiting."),
    ("hard", "What appears to be ______ in the composer's late scores is in fact meticulously notated.",
     "improvisation", ["repetition", "silence", "dissonance"],
     "'What appears to be X is in fact meticulously notated' requires X to be the opposite of precise notation."),
    ("hard", "The essay is valuable less for its conclusions, which are ______, than for the questions it raises.",
     "unremarkable", ["provocative", "extensive", "recent"],
     "'Less for X than for Y' downgrades the conclusions relative to the questions, so the conclusions are ordinary."),
    ("hard", "The policy's effects proved ______: measures intended to reduce congestion increased it within a year.",
     "counterproductive", ["negligible", "gradual", "expensive"],
     "An intended reduction producing an increase is the definition of counterproductive."),
    ("hard", "Her prose is ______ without being obscure: every sentence rewards a second reading but none requires one.",
     "dense", ["plain", "careless", "ornate"],
     "Rewarding rereading without requiring it describes compression, which 'dense' names, while 'obscure' is ruled out."),
    ("hard", "The reforms were ______ rather than systemic, addressing individual complaints as they arose.",
     "piecemeal", ["sweeping", "overdue", "unpopular"],
     "Addressing complaints one at a time contrasts with systemic change; 'piecemeal' names that fragmentary approach."),
    ("hard", "The account is ______ in its detail yet strangely uninformative about the author's own role.",
     "exhaustive", ["scant", "hostile", "secondhand"],
     "'Yet' contrasts abundant detail with a specific silence, so the first term must mean extremely thorough."),
    ("hard", "The evidence for the hypothesis remains ______, resting on a single unreplicated experiment.",
     "tenuous", ["overwhelming", "recent", "contested"],
     "A single unreplicated experiment makes support thin, which 'tenuous' names."),
]

# (difficulty, first_sentence, second_sentence, correct, [distractors], rationale)
TRANSITIONS = [
    ("easy", "The museum offers free entry on the first Sunday of each month.",
     "visitors should expect long queues on those days.",
     "Consequently,", ["Nevertheless,", "For example,", "Previously,"],
     "Free entry causes the crowds, so the transition must signal result."),
    ("easy", "Emperor penguins breed during the Antarctic winter.",
     "they endure temperatures that would kill most other birds.",
     "As a result,", ["In contrast,", "For instance,", "Meanwhile,"],
     "Breeding in winter causes the exposure described, so a result transition is needed."),
    ("easy", "Aluminium is abundant in the earth's crust.",
     "it was once more valuable than gold, because separating it was so difficult.",
     "Nevertheless,", ["Therefore,", "Similarly,", "Afterward,"],
     "Abundance and high value are in tension, so the transition must mark contrast."),
    ("easy", "The soil in the valley retains water well.",
     "farmers there grow crops that would fail on the neighbouring slopes.",
     "Accordingly,", ["However,", "In contrast,", "Beforehand,"],
     "The soil property causes the farming outcome, so the transition signals result."),
    ("easy", "The orchestra rehearsed the passage for three weeks.",
     "the recording was completed in a single take.",
     "Ultimately,", ["Similarly,", "For example,", "Likewise,"],
     "The long rehearsal leads to the final outcome; 'Ultimately' marks that conclusion."),
    ("easy", "Sea ice reflects most of the sunlight that strikes it.",
     "open water absorbs it.",
     "By contrast,", ["Consequently,", "In addition,", "Afterward,"],
     "Reflecting and absorbing are opposed behaviours, so contrast is required."),
    ("medium", "Early telescopes suffered from severe colour fringing.",
     "Newton's reflecting design avoided the problem by using a mirror instead of a lens.",
     "In response,", ["Similarly,", "Regardless,", "Beforehand,"],
     "The new design answers the stated problem, so the transition marks a response to it."),
    ("medium", "The survey found broad public support for the measure.",
     "turnout at the referendum was among the lowest on record.",
     "Even so,", ["Therefore,", "Likewise,", "In particular,"],
     "Support and low turnout are in tension, calling for a concessive contrast."),
    ("medium", "Bamboo reaches full height in a single growing season.",
     "it is harvested on a far shorter cycle than hardwood timber.",
     "For this reason,", ["Nonetheless,", "In contrast,", "Previously,"],
     "Fast growth causes the short harvest cycle, so a causal transition fits."),
    ("medium", "The first draft of the constitution ran to ninety pages.",
     "the ratified text fits on four.",
     "In the end,", ["Similarly,", "Consequently,", "Furthermore,"],
     "The contrast between draft and final length is resolved chronologically by 'In the end'."),
    ("medium", "Most antibiotics target features unique to bacterial cells.",
     "they leave human cells largely unharmed.",
     "As a consequence,", ["Even so,", "In contrast,", "Beforehand,"],
     "The targeting explains the safety, so the transition signals result."),
    ("medium", "Restoring the fresco required matching pigments no longer manufactured.",
     "the conservators ground their own from mineral samples.",
     "Accordingly,", ["Nevertheless,", "In contrast,", "Similarly,"],
     "Grinding their own pigments is the response to the stated difficulty."),
    ("medium", "The company projected that the new plant would open in March.",
     "construction was still unfinished the following December.",
     "In fact,", ["Likewise,", "Therefore,", "For instance,"],
     "The outcome contradicts the projection, which 'In fact' introduces."),
    ("hard", "Standard accounts credit the printing press with the rapid spread of vernacular literature.",
     "manuscripts in vernacular languages circulated widely for a century beforehand.",
     "In fact,", ["Consequently,", "Similarly,", "As a result,"],
     "The second sentence corrects the standard account rather than following from it."),
    ("hard", "The alloy resists corrosion and weighs a third less than steel.",
     "its cost has confined it to aerospace applications.",
     "Still,", ["Thus,", "Indeed,", "Likewise,"],
     "Advantages are followed by a limitation that overrides them, so a concessive contrast is needed."),
    ("hard", "The model reproduced the observed migration routes almost exactly.",
     "it failed to predict the timing of departure, which its authors attribute to omitted weather variables.",
     "That said,", ["Accordingly,", "In turn,", "By comparison,"],
     "A success followed by an acknowledged shortcoming calls for a concessive qualification."),
    ("hard", "Excavations at the site have recovered thousands of animal bones but almost no cooking hearths.",
     "the assemblage may represent butchery carried out for consumption elsewhere.",
     "Taken together,", ["Conversely,", "Beforehand,", "Nonetheless,"],
     "The inference draws on both observations at once, which 'Taken together' signals."),
    ("hard", "Critics charged that the new tax would drive small firms out of the district.",
     "registrations of new businesses rose in each of the three following years.",
     "In the event,", ["Therefore,", "Similarly,", "In addition,"],
     "The outcome contradicts the prediction; 'In the event' introduces what actually happened."),
    ("hard", "Neural networks and human learners both improve with practice on a task.",
     "the resemblance breaks down under distribution shift, where humans generalize and networks often do not.",
     "Beyond that point,", ["Consequently,", "Likewise,", "For example,"],
     "The second sentence limits the analogy just drawn, marking where it stops holding."),
]

# (difficulty, [notes], goal, correct, [distractors], rationale)
SYNTHESIS = [
    ("easy",
     ["The kakapo is a flightless parrot native to New Zealand.",
      "It is nocturnal.", "Adults can weigh up to 4 kilograms.",
      "Fewer than 250 individuals remain."],
     "emphasize the kakapo's conservation status",
     "Fewer than 250 kakapo remain, making the flightless New Zealand parrot one of the world's rarest birds.",
     ["The kakapo is a nocturnal parrot native to New Zealand.",
      "Adult kakapo can weigh up to 4 kilograms.",
      "The kakapo is flightless and nocturnal."],
     "Only the choice citing the remaining population addresses conservation status."),
    ("easy",
     ["The Rosetta Stone was found in 1799.",
      "It carries the same decree in three scripts.",
      "The scripts are hieroglyphic, Demotic, and Greek.",
      "Scholars used the Greek to decipher the hieroglyphs."],
     "explain how the stone made decipherment possible",
     "Because the stone repeats one decree in hieroglyphic, Demotic, and Greek, scholars could use the Greek to decipher the hieroglyphs.",
     ["The Rosetta Stone was found in 1799.",
      "The Rosetta Stone carries a decree in three scripts.",
      "The Rosetta Stone is written partly in Greek."],
     "Only the choice linking the known script to the unknown one explains decipherment."),
    ("easy",
     ["Honey does not spoil.", "Sealed jars have been found in ancient tombs.",
      "Its low water content inhibits bacteria.", "It is also highly acidic."],
     "explain why honey does not spoil",
     "Honey resists spoilage because its low water content and high acidity together inhibit bacteria.",
     ["Sealed jars of honey have been found in ancient tombs.",
      "Honey does not spoil, even after thousands of years.",
      "Honey is both acidic and low in water."],
     "The goal is causal, and only one choice names both properties as the reason."),
    ("medium",
     ["The Silk Road was not a single road.",
      "It was a network of overland and maritime routes.",
      "It operated from roughly 130 BCE to 1450 CE.",
      "It carried goods, technologies, religions, and disease."],
     "emphasize the breadth of what the routes transmitted",
     "Along its overland and maritime routes the Silk Road carried not only goods but technologies, religions, and disease.",
     ["The Silk Road operated from roughly 130 BCE to 1450 CE.",
      "The Silk Road was a network rather than a single road.",
      "The Silk Road included both overland and maritime routes."],
     "Only one choice lists the range of things transmitted rather than the network's shape or dates."),
    ("medium",
     ["Ada Lovelace worked with Charles Babbage in the 1840s.",
      "She wrote notes on his proposed Analytical Engine.",
      "Her notes include an algorithm for computing Bernoulli numbers.",
      "She also argued the machine could manipulate symbols, not just numbers."],
     "emphasize the conceptual leap in Lovelace's notes",
     "Lovelace argued that the Analytical Engine could manipulate symbols rather than merely calculate, anticipating uses beyond arithmetic.",
     ["Ada Lovelace worked with Charles Babbage in the 1840s.",
      "Lovelace's notes include an algorithm for Bernoulli numbers.",
      "Lovelace wrote extensive notes on the Analytical Engine."],
     "The conceptual leap is the claim about symbols; the algorithm and the collaboration are context."),
    ("medium",
     ["Mount Tambora erupted in 1815.",
      "It ejected roughly 100 cubic kilometres of material.",
      "Global temperatures fell by about 0.5°C the following year.",
      "1816 became known as the year without a summer."],
     "emphasize the eruption's global climatic effect",
     "Tambora's 1815 eruption lowered global temperatures by about 0.5°C, producing the year without a summer in 1816.",
     ["Mount Tambora erupted in 1815, ejecting about 100 cubic kilometres of material.",
      "Mount Tambora is a volcano that erupted in 1815.",
      "The year 1816 was unusually cold in many places."],
     "Only one choice ties the eruption to the measured global temperature effect."),
    ("medium",
     ["Coffee rust is a fungal disease of coffee plants.",
      "It first devastated plantations in Ceylon in the 1870s.",
      "Growers there replaced coffee with tea.",
      "Ceylon tea remains a major export today."],
     "emphasize the long-term economic consequence of the outbreak",
     "After coffee rust destroyed Ceylon's plantations in the 1870s, growers switched to tea, which remains a major export today.",
     ["Coffee rust is a fungal disease that attacks coffee plants.",
      "Coffee rust reached Ceylon in the 1870s.",
      "Ceylon growers replaced their coffee plants with tea."],
     "The long-term consequence requires connecting the outbreak to tea's continuing importance."),
    ("hard",
     ["The Antikythera mechanism dates to roughly the second century BCE.",
      "It contains at least 30 bronze gears.",
      "It modelled the motions of the sun and moon.",
      "No comparably geared device is known for the next thousand years.",
      "Historians have revised assumptions about ancient engineering."],
     "emphasize why the mechanism forced a reassessment of ancient technology",
     "Because no comparably geared device appears for a thousand years afterward, the mechanism has forced historians to revise what they assumed ancient engineering could achieve.",
     ["The Antikythera mechanism contains at least 30 bronze gears.",
      "The Antikythera mechanism modelled the motions of the sun and moon.",
      "The Antikythera mechanism dates to roughly the second century BCE."],
     "The reassessment follows from the thousand-year gap, which only one choice mentions."),
    ("hard",
     ["Nauru was once among the richest countries per capita.",
      "Its wealth came from phosphate deposits.",
      "The deposits were largely exhausted by the 1990s.",
      "Mining left about 80 percent of the island uninhabitable.",
      "The country now imports nearly all its food."],
     "emphasize the lasting cost of the island's phosphate economy",
     "Phosphate mining left roughly 80 percent of Nauru uninhabitable and the country dependent on imported food once the deposits ran out.",
     ["Nauru was once among the richest countries per capita.",
      "Nauru's wealth came from its phosphate deposits.",
      "Nauru's phosphate deposits were exhausted by the 1990s."],
     "The lasting cost is the ruined land and import dependence, not the former wealth or the timeline."),
    ("hard",
     ["Lake Nyos is a crater lake in Cameroon.",
      "Carbon dioxide seeps into its depths from magma below.",
      "In 1986 the lake released a large cloud of the gas.",
      "The cloud suffocated more than 1,700 people.",
      "Degassing pipes were installed beginning in 2001."],
     "emphasize the measure taken to prevent a recurrence",
     "Since 2001, degassing pipes have vented carbon dioxide from Lake Nyos to prevent another release like the one that killed more than 1,700 people in 1986.",
     ["Lake Nyos is a crater lake in Cameroon fed by volcanic gas.",
      "In 1986 Lake Nyos released a cloud of carbon dioxide.",
      "Carbon dioxide seeps into Lake Nyos from magma below."],
     "Only one choice describes the preventive measure rather than the hazard or the disaster."),
]


# (difficulty, domain, skill, passage, stem, correct, [distractors], rationale)
PASSAGES = [
    ("easy", "information_ideas", "Central Ideas and Details",
     "The pistol shrimp hunts without touching its prey. Snapping one oversized claw shut produces a bubble that collapses so violently it generates a shock wave, stunning small fish at a distance of several centimetres.",
     "Which choice best states the main idea of the text?",
     "The pistol shrimp stuns prey at a distance using a shock wave produced by its claw.",
     ["The pistol shrimp has one claw larger than the other.",
      "The pistol shrimp is among the loudest animals in the ocean.",
      "Small fish are the pistol shrimp's only prey."],
     "The text describes the claw, the collapsing bubble, and the resulting shock wave that stuns prey at a distance."),
    ("easy", "information_ideas", "Central Ideas and Details",
     "Venice was built on soft mud, which cannot bear the weight of stone. Its builders drove millions of wooden piles into the seabed until they reached firmer clay beneath. Submerged in oxygen-poor water, the wood never rotted, and much of it still holds the city up.",
     "Which choice best states the main idea of the text?",
     "Venice stands on wooden piles that have survived because they sit in oxygen-poor water.",
     ["Venice was built on ground too soft to support any structure.",
      "Wooden piles are stronger than stone foundations.",
      "Venice's builders preferred wood to stone for aesthetic reasons."],
     "The text explains the soft ground, the piles driven to firmer clay, and why the wood survived."),
    ("easy", "information_ideas", "Central Ideas and Details",
     "Naked mole rats live in underground colonies with a single breeding female, an arrangement otherwise seen in insects rather than mammals. Workers dig tunnels with their teeth, and the colony can extend for kilometres beneath the soil.",
     "Which choice best states the main idea of the text?",
     "Naked mole rats live in colonies organized in a way rarely found among mammals.",
     ["Naked mole rats dig tunnels using their teeth.",
      "Naked mole rat colonies extend for kilometres.",
      "Insects and mammals often share social structures."],
     "The text's emphasis is the insect-like social structure, unusual for a mammal; the digging and extent are supporting details."),
    ("easy", "information_ideas", "Inferences",
     "Desert plants face a dilemma: the pores they open to take in carbon dioxide also release water. Many cacti open theirs only after dark, storing the gas until daylight allows photosynthesis to proceed.",
     "Which choice most logically completes the text?",
     "Opening the pores at night therefore reduces the water a cactus loses.",
     ["Cacti therefore photosynthesize more efficiently at night.",
      "Cacti therefore do not require carbon dioxide.",
      "Desert plants therefore keep their pores permanently closed."],
     "Water loss through open pores is the stated cost, and darkness is cooler, so night opening limits that loss."),
    ("easy", "information_ideas", "Inferences",
     "Tree rings grow wider in years with ample rainfall and narrower in dry ones. A timber beam salvaged from a ruined farmhouse shows a run of unusually narrow rings near its outer edge.",
     "Which choice most logically completes the text?",
     "The final years of the tree's growth were most likely unusually dry.",
     ["The tree was most likely cut down before it matured.",
      "The farmhouse was most likely built during a wet period.",
      "The beam most likely came from a species that grows slowly."],
     "Narrow rings indicate dry years, and rings near the outer edge are the most recent growth."),
    ("easy", "information_ideas", "Command of Evidence (Textual)",
     "A student claims that street trees measurably reduce summer temperatures in city neighbourhoods.",
     "Which finding, if true, would most directly support the student's claim?",
     "Sensors recorded afternoon temperatures three degrees lower on tree-lined streets than on comparable treeless streets nearby.",
     ["Street trees in the city are most commonly planted in spring.",
      "Residents report that tree-lined streets are more attractive.",
      "Street trees require regular pruning to remain healthy."],
     "The claim is about measured temperature reduction, and only the sensor comparison measures it."),
    ("medium", "information_ideas", "Central Ideas and Details",
     "Historians once treated the Library of Alexandria's destruction as a single catastrophic fire. Surviving records suggest something slower: shrinking budgets, the expulsion of scholars, and centuries of neglect, with fire only one episode among many. The library did not burn down so much as wind down.",
     "Which choice best states the main idea of the text?",
     "The library's loss was a gradual decline rather than one destructive event.",
     ["The library was never actually destroyed by fire.",
      "The library's scholars were responsible for its decline.",
      "Records of the library's history are largely unreliable."],
     "The text contrasts the single-fire account with budgets, expulsions, and neglect, concluding it 'wound down'."),
    ("medium", "information_ideas", "Central Ideas and Details",
     "The Voynich manuscript has resisted every attempt at translation since its rediscovery in 1912. Statistical analyses show its symbol frequencies behave like those of a natural language rather than random noise, yet no proposed decipherment has been reproducible. The text is either an unknown script or an unusually sophisticated hoax.",
     "Which choice best states the main idea of the text?",
     "The manuscript's linguistic statistics rule out randomness but have not settled whether it encodes a real language.",
     ["The manuscript is almost certainly an elaborate hoax.",
      "The manuscript was written in a language now extinct.",
      "Statistical analysis has produced a reproducible decipherment."],
     "The text reports language-like statistics, no reproducible decipherment, and two remaining possibilities."),
    ("medium", "information_ideas", "Inferences",
     "Migratory songbirds navigate partly by the stars. Birds raised in planetariums under an artificial sky oriented themselves toward whatever direction that sky designated as north, even when it conflicted with the earth's magnetic field.",
     "Which choice most logically completes the text?",
     "For these birds, celestial cues can override magnetic ones.",
     ["These birds cannot detect magnetic fields at all.",
      "Birds raised indoors lose the ability to navigate.",
      "Artificial skies disorient birds entirely."],
     "The birds followed the artificial sky even when it conflicted with the magnetic field, so the celestial cue took precedence."),
    ("medium", "information_ideas", "Inferences",
     "A pottery workshop's output can often be traced by the clay it used. Vessels excavated at an inland fortress match, in mineral composition, clay beds found only on a coastal plain two hundred kilometres away. No kiln has been found at the fortress.",
     "Which choice most logically completes the text?",
     "The vessels were most likely made on the coastal plain and transported inland.",
     ["The fortress most likely imported clay and fired it on site.",
      "The mineral analysis is most likely mistaken.",
      "The coastal plain was most likely settled from the fortress."],
     "Coastal clay plus no kiln at the fortress points to manufacture at the source and transport of finished vessels."),
    ("medium", "information_ideas", "Command of Evidence (Textual)",
     "Musicologist Farah Nasser argues that the sudden popularity of the twelve-string guitar in the 1960s owed less to its sound than to its visibility: a handful of televised performances put the instrument in front of millions.",
     "Which finding, if true, would most strongly support Nasser's argument?",
     "Sales of twelve-string guitars rose sharply in the weeks immediately following each televised performance, with no change in their price or design.",
     ["Twelve-string guitars produce a fuller sound than six-string models.",
      "Several prominent musicians preferred twelve-string guitars.",
      "Twelve-string guitars were more difficult to tune than six-string models."],
     "Nasser attributes popularity to visibility, so evidence must tie sales to the broadcasts rather than to the instrument's qualities."),
    ("medium", "information_ideas", "Command of Evidence (Quantitative)",
     "A city compared recycling rates before and after switching to fortnightly collection.\n\n| District | Before | After |\n|---|---|---|\n| Ashgrove | 41% | 52% |\n| Bellhaven | 38% | 47% |\n| Cranwell | 45% | 44% |\n| Dunmore | 36% | 49% |\n\nAn official concluded that the change raised recycling in most districts.",
     "Which choice best uses data from the table to support the official's conclusion?",
     "Rates rose in three of the four districts, by between 9 and 13 percentage points.",
     ["Cranwell's rate fell slightly, from 45% to 44%.",
      "Ashgrove had the highest rate after the change, at 52%.",
      "Dunmore had the lowest rate before the change, at 36%."],
     "The conclusion concerns increases across most districts, so the evidence must report their number and size."),
    ("hard", "information_ideas", "Central Ideas and Details",
     "Accounts of the Irish famine often centre on the potato blight. Economic historian Declan Mulready does not dispute the pathogen's role but notes that Ireland continued exporting grain, butter, and livestock throughout the worst years. The catastrophe, on his account, lay less in what the land failed to produce than in where its produce went.",
     "Which choice best states the main idea of the text?",
     "Mulready locates the famine's severity in the distribution of Irish food rather than in crop failure alone.",
     ["Mulready denies that the potato blight affected Ireland.",
      "Mulready argues that Ireland produced more food than it needed.",
      "Mulready believes the famine has been exaggerated by historians."],
     "Mulready accepts the blight but stresses continued exports, concluding the issue was where produce went."),
    ("hard", "information_ideas", "Inferences",
     "Radiocarbon dating assumes a known atmospheric ratio of carbon isotopes. Fossil fuel burning releases carbon so old that it contains no radiocarbon at all, diluting the atmospheric proportion measurably since the nineteenth century.",
     "Which choice most logically completes the text?",
     "Organic material formed recently may therefore appear older than it is when dated by this method without correction.",
     ["Radiocarbon dating is therefore unusable for any modern sample.",
      "Fossil fuels therefore contain more radiocarbon than living tissue.",
      "The atmospheric ratio has therefore remained constant since the nineteenth century."],
     "Dilution lowers the radiocarbon proportion, and a lower proportion reads as greater age unless corrected."),
    ("hard", "information_ideas", "Inferences",
     "A drug performed well in trials conducted at high-altitude clinics but showed no benefit at sea level. The compound's proposed mechanism depends on binding to haemoglobin, and residents at altitude carry substantially more haemoglobin than sea-level populations.",
     "Which choice most logically completes the text?",
     "The drug's apparent effectiveness may depend on the elevated haemoglobin levels found at altitude rather than on altitude itself.",
     ["The drug is therefore ineffective under all conditions.",
      "Altitude therefore causes the condition the drug treats.",
      "Haemoglobin levels therefore have no bearing on the drug's action."],
     "The mechanism runs through haemoglobin, which is elevated at altitude, so the binding target rather than elevation explains the pattern."),
    ("hard", "information_ideas", "Command of Evidence (Textual)",
     "Archaeologist Sunil Rao proposes that a settlement's unusual grain-storage pits were communal rather than household property. Critics note that communal and household storage can look identical once abandoned.",
     "Which finding, if true, would most weaken the critics' objection?",
     "The pits are clustered in a single open area at the settlement's centre, away from every identified dwelling.",
     ["The pits were all dug to approximately the same depth.",
      "Grain residue in the pits comes from several different crops.",
      "The pits remained in use for several generations."],
     "Placement away from dwellings and grouped centrally distinguishes communal from household storage, which is exactly what the critics say cannot be told apart."),
    ("hard", "information_ideas", "Command of Evidence (Quantitative)",
     "Researchers measured seedling survival under four canopy conditions after one year.\n\n| Canopy cover | Survival |\n|---|---|\n| 0% (open) | 22% |\n| 25% | 58% |\n| 50% | 71% |\n| 90% | 34% |\n\nThey concluded that seedlings of this species survive best under partial rather than full or absent canopy.",
     "Which choice best uses data from the table to support the researchers' conclusion?",
     "Survival peaked at 71% under 50% cover, exceeding both the open plots at 22% and the densest canopy at 34%.",
     ["Survival under 25% cover was 58%.",
      "Survival was lowest in the open plots, at 22%.",
      "Survival declined between 50% and 90% cover."],
     "The conclusion is that the middle of the range is best, so the evidence must compare the peak against both extremes."),
    ("easy", "craft_structure", "Text Structure and Purpose",
     "Most spiders build a fresh web each day. The bolas spider does not build one at all. It dangles a single silk line tipped with a sticky globule and swings it at passing moths, which it attracts by mimicking their scent.",
     "Which choice best states the main purpose of the text?",
     "To describe a hunting method that departs from typical spider behaviour",
     ["To explain how spiders produce silk",
      "To argue that bolas spiders are more efficient hunters than other spiders",
      "To compare the diets of different spider species"],
     "The text sets up the usual pattern, marks the bolas spider as an exception, and details that exception."),
    ("easy", "craft_structure", "Text Structure and Purpose",
     "The metric system was designed to be reproducible from nature: the metre was defined as a fraction of the earth's meridian. That definition proved impractical to check, and the metre is now fixed by the distance light travels in a specified fraction of a second.",
     "Which choice best describes the overall structure of the text?",
     "It presents an original definition and then explains what replaced it and why.",
     ["It argues that the metric system should be abandoned.",
      "It compares the metric system with older measurement systems.",
      "It describes how the earth's meridian was first measured."],
     "The text gives the original meridian-based definition, notes it was impractical, and states the current one."),
    ("medium", "craft_structure", "Text Structure and Purpose",
     "Conventional wisdom holds that adding lanes relieves traffic congestion. Transport data repeatedly show otherwise: within a few years, new capacity fills with trips that were not previously made at all. Engineers call the effect induced demand, and it means a wider road often carries more vehicles at the same crawling speed.",
     "Which choice best states the main purpose of the text?",
     "To present evidence that contradicts a common assumption and name the mechanism behind it",
     ["To recommend a specific transport policy for cities",
      "To describe how traffic engineers measure congestion",
      "To compare road widening with public transport investment"],
     "The text states the assumption, gives contrary data, and names induced demand as the mechanism."),
    ("medium", "craft_structure", "Text Structure and Purpose",
     "The following is adapted from a novel. The narrator has returned to a house she left as a child.\n\nThe banister was exactly where my hand expected it, which was worse than if it had been moved. Everything had been kept. Nothing had been kept for me.",
     "Which choice best describes the function of the final two sentences?",
     "They draw a distinction between preservation and welcome that unsettles the narrator.",
     ["They explain why the narrator originally left the house.",
      "They describe the physical condition of the house in detail.",
      "They indicate that the house has new occupants."],
     "'Everything had been kept. Nothing had been kept for me.' separates the house's preservation from any claim on the narrator."),
    ("hard", "craft_structure", "Text Structure and Purpose",
     "Ecologists have long treated invasive species as uniformly damaging. Botanist Ingrid Sorensen resists the framing without denying the harm. On degraded land where native seed banks are exhausted, she argues, fast-colonizing non-natives can stabilize soil and shade out bare ground, creating conditions under which natives can later be reintroduced. The label describes an origin, not an effect.",
     "Which choice best describes the function of the final sentence in the text?",
     "It states the conceptual point the preceding example was offered to establish.",
     ["It concedes a limitation in Sorensen's argument.",
      "It introduces a new line of evidence about seed banks.",
      "It restates the conventional ecological position."],
     "'The label describes an origin, not an effect' generalizes from the degraded-land case into the claim the passage is making."),
    ("hard", "craft_structure", "Text Structure and Purpose",
     "Translators of ancient poetry face a problem archaeologists do not. A broken pot can be displayed with its gaps visible, its incompleteness part of what the viewer sees. A translation cannot show its own fractures without ceasing to read as a poem, so the losses it incurs are precisely the ones its reader will never know about.",
     "Which choice best states the main purpose of the text?",
     "To explain why the losses in a translation are harder to perceive than those in a physical artifact",
     ["To argue that ancient poetry should not be translated",
      "To describe the methods archaeologists use to restore pottery",
      "To compare the training of translators and archaeologists"],
     "The pot's visible gaps are contrasted with a translation whose fractures cannot show, making its losses invisible to readers."),
]


def build(rng):
    out = []

    for difficulty, domain, skill, passage, stem, correct, distractors, why in PASSAGES:
        options = [correct] + list(distractors)
        rng.shuffle(options)
        ids = "ABCD"
        out.append({
            "section": "reading_writing", "domain": domain, "skill": skill,
            "difficulty": difficulty, "question_type": "multiple_choice",
            "stimulus": passage, "stem": stem,
            "choices": [{"id": ids[i], "text": v} for i, v in enumerate(options)],
            "correct_answer": ids[options.index(correct)],
            "rationale": why, "source": "self_authored",
        })

    for difficulty, sentence, correct, distractors, why in WORDS_IN_CONTEXT:
        options = [correct] + list(distractors)
        rng.shuffle(options)
        ids = "ABCD"
        out.append({
            "section": "reading_writing", "domain": "craft_structure",
            "skill": "Words in Context", "difficulty": difficulty,
            "question_type": "multiple_choice", "stimulus": sentence,
            "stem": WIC_STEM,
            "choices": [{"id": ids[i], "text": v} for i, v in enumerate(options)],
            "correct_answer": ids[options.index(correct)],
            "rationale": why, "source": "self_authored",
        })

    for difficulty, first, second, correct, distractors, why in TRANSITIONS:
        options = [correct] + list(distractors)
        rng.shuffle(options)
        ids = "ABCD"
        out.append({
            "section": "reading_writing", "domain": "expression_of_ideas",
            "skill": "Transitions", "difficulty": difficulty,
            "question_type": "multiple_choice",
            "stimulus": f"{first} ______ {second}",
            "stem": TRANS_STEM,
            "choices": [{"id": ids[i], "text": v} for i, v in enumerate(options)],
            "correct_answer": ids[options.index(correct)],
            "rationale": why, "source": "self_authored",
        })

    for difficulty, notes, goal, correct, distractors, why in SYNTHESIS:
        options = [correct] + list(distractors)
        rng.shuffle(options)
        ids = "ABCD"
        bullets = "\n".join(f"- {n}" for n in notes)
        out.append({
            "section": "reading_writing", "domain": "expression_of_ideas",
            "skill": "Rhetorical Synthesis", "difficulty": difficulty,
            "question_type": "multiple_choice",
            "stimulus": f"While researching a topic, a student took the following notes:\n\n{bullets}",
            "stem": f"The student wants to {goal}. Which choice most effectively uses "
                    f"relevant information from the notes to accomplish this goal?",
            "choices": [{"id": ids[i], "text": v} for i, v in enumerate(options)],
            "correct_answer": ids[options.index(correct)],
            "rationale": why, "source": "self_authored",
        })

    rng.shuffle(out)
    return out


def main():
    p = argparse.ArgumentParser(description="Expand authored R&W corpora.")
    p.add_argument("--seed", type=int, default=23)
    p.add_argument("--out", required=True)
    args = p.parse_args()

    questions = build(random.Random(args.seed))
    with open(args.out, "w", encoding="utf-8") as f:
        json.dump({
            "_note": "Expanded by scripts/generate_rw_content.py from authored "
                     "corpora. Original items.",
            "questions": questions,
        }, f, indent=2, ensure_ascii=False)

    counts = {}
    for q in questions:
        counts[(q["domain"], q["difficulty"])] = counts.get((q["domain"], q["difficulty"]), 0) + 1
    print(f"wrote {len(questions)} questions to {args.out}")
    for k, v in sorted(counts.items()):
        print(f"  {k[0]:24} {k[1]:7} {v}")


if __name__ == "__main__":
    main()
