"""Expands compact authored corpora into Reading & Writing bank items.

The content here is authored, not templated - each entry is a written sentence
or note set with its own key and distractors. What the script removes is the
JSON boilerplate, not the writing: a Words-in-Context item is a one-line tuple
here instead of twenty lines of schema.

Skills covered: Words in Context and Text Structure and Purpose (Craft &
Structure), Transitions and Rhetorical Synthesis (Expression of Ideas).

Usage:
    python -m scripts.generate_rw_content --out data/question_bank/rw_generated.json
"""

import argparse
import json
import random

WIC_STEM = "Which choice completes the text with the most logical and precise word or phrase?"
TRANS_STEM = "Which choice completes the text with the most logical transition?"

# (difficulty, sentence_with_blank, correct, [distractors], rationale)
WORDS_IN_CONTEXT = [
    ("easy", "The instructions were so ______ that even first-time users assembled the shelf without difficulty.",
     "clear", ["technical", "lengthy", "optional"],
     "Assembling it without difficulty indicates instructions that were easy to follow."),
    ("easy", "Rainfall in the region is ______: some years bring flooding, others almost none at all.",
     "erratic", ["abundant", "predictable", "seasonal"],
     "The colon describes wide swings between extremes, which is what 'erratic' names; 'predictable' is its opposite."),
    ("easy", "The mayor's speech was deliberately ______, lasting under four minutes and naming only one policy.",
     "brief", ["rambling", "hostile", "musical"],
     "Under four minutes and one policy describes shortness, which 'brief' names."),
    ("easy", "Because the fossil was so ______, researchers could identify individual feather barbs.",
     "well preserved", ["fragmentary", "common", "distant"],
     "Seeing individual barbs requires exceptional preservation; 'fragmentary' contradicts it."),
    ("easy", "The new alloy is ______ enough to be shaped by hand yet strong enough to bear a load.",
     "pliable", ["brittle", "opaque", "costly"],
     "Being shaped by hand requires flexibility, which 'pliable' names; 'brittle' is the opposite."),
    ("easy", "Critics found the sequel ______, noting that it repeated the original almost scene for scene.",
     "derivative", ["inventive", "concise", "expensive"],
     "Repeating the original scene for scene is the definition of derivative work."),
    ("easy", "The library's collection of maps is ______, spanning six centuries and four continents.",
     "extensive", ["meager", "recent", "fragile"],
     "Six centuries and four continents describes great range, which 'extensive' names."),
    ("easy", "Her argument was ______: each claim followed from the one before it.",
     "coherent", ["disjointed", "brief", "popular"],
     "Claims following from one another is coherence; 'disjointed' is the opposite."),
    ("medium", "The committee's findings were ______ by the very data the committee had commissioned.",
     "undermined", ["confirmed", "published", "requested"],
     "'By the very data it commissioned' sets up an ironic reversal, so the findings were weakened, not supported."),
    ("medium", "Far from being ______, the treaty's language was chosen to leave each signatory room to interpret it.",
     "precise", ["lengthy", "recent", "translated"],
     "'Far from being' contrasts with language leaving room for interpretation, whose opposite is precision."),
    ("medium", "The artist's late work is notably ______, stripping away the ornament that filled her early canvases.",
     "austere", ["cluttered", "colorful", "commercial"],
     "Stripping away ornament produces austerity; 'cluttered' describes what was removed."),
    ("medium", "Although the theory was initially ______, within a decade it appeared in every introductory textbook.",
     "marginal", ["dominant", "elegant", "testable"],
     "'Although' contrasts the later ubiquity with an obscure beginning, which 'marginal' names."),
    ("medium", "The editor's revisions were ______: she changed three commas and left the argument untouched.",
     "cosmetic", ["substantial", "hostile", "delayed"],
     "Changing three commas while leaving the argument alone is surface-level, which 'cosmetic' names."),
    ("medium", "Rather than ______ the conflicting accounts, the historian presents both and explains why they differ.",
     "reconciling", ["recording", "translating", "publishing"],
     "The contrast is with presenting both accounts separately, so the rejected option is forcing them into agreement."),
    ("medium", "The device's appeal is its ______: it performs one task, and requires no instructions to operate.",
     "simplicity", ["versatility", "durability", "novelty"],
     "One task and no instructions describes simplicity; 'versatility' would mean many tasks."),
    ("medium", "The prosecution's case rested on ______ evidence, since no witness had seen the act itself.",
     "circumstantial", ["direct", "forged", "abundant"],
     "Evidence in the absence of an eyewitness to the act is circumstantial, the opposite of direct."),
    ("medium", "The novel's structure is ______, moving between three centuries without signalling the shifts.",
     "elliptical", ["chronological", "repetitive", "conventional"],
     "Unsignalled jumps across centuries leave gaps for the reader to bridge, which 'elliptical' names."),
    ("hard", "The study's conclusions are ______ by its sample, which was drawn entirely from one hospital.",
     "circumscribed", ["corroborated", "popularized", "duplicated"],
     "A sample from a single hospital limits how far conclusions extend; 'circumscribed' names that limiting."),
    ("hard", "What appears to be ______ in the composer's late scores is in fact meticulously notated.",
     "improvisation", ["repetition", "silence", "dissonance"],
     "'What appears to be X is in fact meticulously notated' requires X to be the opposite of precise notation."),
    ("hard", "The essay is valuable less for its conclusions, which are ______, than for the questions it raises.",
     "unremarkable", ["provocative", "extensive", "recent"],
     "'Less for X than for Y' downgrades the conclusions relative to the questions, so the conclusions are ordinary."),
    ("hard", "The policy's effects proved ______: measures intended to reduce congestion increased it within a year.",
     "counterproductive", ["negligible", "gradual", "expensive"],
     "An intended reduction producing an increase is the definition of counterproductive."),
    ("hard", "Her prose is ______ without being obscure: every sentence rewards a second reading but none requires one.",
     "dense", ["plain", "careless", "ornate"],
     "Rewarding rereading without requiring it describes compression, which 'dense' names, while 'obscure' is ruled out."),
    ("hard", "The reforms were ______ rather than systemic, addressing individual complaints as they arose.",
     "piecemeal", ["sweeping", "overdue", "unpopular"],
     "Addressing complaints one at a time contrasts with systemic change; 'piecemeal' names that fragmentary approach."),
    ("hard", "The account is ______ in its detail yet strangely uninformative about the author's own role.",
     "exhaustive", ["scant", "hostile", "secondhand"],
     "'Yet' contrasts abundant detail with a specific silence, so the first term must mean extremely thorough."),
    ("hard", "The evidence for the hypothesis remains ______, resting on a single unreplicated experiment.",
     "tenuous", ["overwhelming", "recent", "contested"],
     "A single unreplicated experiment makes support thin, which 'tenuous' names."),
    ("easy", "The path along the cliff is ______, so the guide advised walking single file.",
     "narrow", ["scenic", "ancient", "popular"],
     "Walking single file is a response to limited width, which 'narrow' names."),
    ("easy", "The report was ______ enough that the council read it in a single sitting.",
     "concise", ["exhaustive", "technical", "controversial"],
     "Reading it in one sitting indicates shortness; 'exhaustive' would suggest the opposite."),
    ("easy", "Her account of the voyage is ______: she recorded the weather every four hours for two years.",
     "detailed", ["vague", "secondhand", "brief"],
     "Recording weather every four hours for two years is exhaustive detail."),
    ("easy", "The bridge proved ______, carrying traffic for over a century with only minor repairs.",
     "durable", ["decorative", "costly", "temporary"],
     "A century of service with minor repairs describes durability; 'temporary' contradicts it."),
    ("easy", "Because the species is ______, biologists must travel to a single island to observe it.",
     "localized", ["widespread", "nocturnal", "aggressive"],
     "Being found in only one place is what forces the travel, which 'localized' names."),
    ("easy", "The teacher's explanation was ______, and several students asked her to repeat it.",
     "muddled", ["memorable", "lengthy", "amusing"],
     "Students needing it repeated indicates the explanation was unclear."),
    ("easy", "The recipe is ______, calling for only three ingredients and one pan.",
     "straightforward", ["elaborate", "traditional", "expensive"],
     "Three ingredients and one pan describes simplicity."),
    ("easy", "The mural had ______ over the decades, its blues fading almost to grey.",
     "deteriorated", ["brightened", "expanded", "sold"],
     "Colors fading to grey describes decline, which 'deteriorated' names."),
    ("medium", "The negotiator's manner was ______, giving no hint of which concession she would accept.",
     "inscrutable", ["genial", "hurried", "formal"],
     "Giving no hint of her position describes an unreadable manner."),
    ("medium", "Although the museum bills the collection as complete, it is in fact ______: three of the panels are copies.",
     "composite", ["priceless", "immense", "fragile"],
     "Some panels being copies makes the collection assembled from mixed sources rather than uniformly original."),
    ("medium", "The policy was ______ from the start, since the agency charged with enforcing it had no inspectors.",
     "unenforceable", ["unpopular", "expensive", "temporary"],
     "Having no inspectors is precisely what makes enforcement impossible."),
    ("medium", "His influence on the field is ______, visible in the vocabulary his critics use to attack him.",
     "pervasive", ["diminishing", "recent", "disputed"],
     "Even opponents using his vocabulary shows influence that has spread everywhere."),
    ("medium", "The two accounts are not contradictory so much as ______: each describes a different stage of the process.",
     "complementary", ["identical", "unreliable", "outdated"],
     "Describing different stages means the accounts fit together rather than conflict."),
    ("medium", "The instrument's readings were ______, drifting by several degrees over the course of an hour.",
     "unstable", ["precise", "automated", "encrypted"],
     "Drifting readings are the opposite of steady, which 'unstable' names."),
    ("medium", "The author's tone is ______, treating even the gravest episodes with a wry detachment.",
     "ironic", ["earnest", "hostile", "academic"],
     "Wry detachment applied to grave matters describes irony; 'earnest' is its opposite."),
    ("medium", "The discovery was ______ rather than planned: the team had been searching for something else entirely.",
     "incidental", ["overdue", "expensive", "collaborative"],
     "Finding something while looking for something else is an incidental discovery."),
    ("medium", "The regulations are ______, leaving inspectors to decide case by case what counts as compliance.",
     "open-ended", ["stringent", "obsolete", "translated"],
     "Leaving decisions to inspectors indicates rules that do not specify outcomes."),
    ("hard", "The argument is ______: its conclusion is smuggled into the premise it claims to establish.",
     "circular", ["persuasive", "novel", "lengthy"],
     "A conclusion contained in its own premise is the definition of a circular argument."),
    ("hard", "Her reading of the poem is ______, drawing meaning from a comma that other editors have removed.",
     "idiosyncratic", ["conventional", "hurried", "collaborative"],
     "Resting on a mark other editors delete makes the reading peculiar to her."),
    ("hard", "The committee's endorsement was ______, hedged with so many conditions that it amounted to a refusal.",
     "nominal", ["enthusiastic", "unanimous", "belated"],
     "An endorsement in name only, undercut by conditions, is nominal."),
    ("hard", "The technique's advantage is ______: it is faster only when the sample is already pure.",
     "conditional", ["substantial", "permanent", "theoretical"],
     "An advantage that holds only in a specific case is conditional."),
    ("hard", "Far from ______ the debate, the new data gave each side fresh material.",
     "settling", ["prolonging", "publicizing", "funding"],
     "'Far from' contrasts with both sides gaining material, whose opposite is resolving the dispute."),
    ("hard", "The style is ______, borrowing a cadence from oral storytelling that the written form rarely admits.",
     "anomalous", ["derivative", "ornate", "restrained"],
     "Admitting what the written form rarely allows makes the style an exception."),
    ("hard", "The record is ______ for the crucial decade: two ledgers survive, and neither covers a full year.",
     "fragmentary", ["voluminous", "contested", "duplicated"],
     "Two partial ledgers constitute broken, incomplete evidence."),
    ("hard", "The reforms were ______ by the very officials charged with carrying them out.",
     "obstructed", ["accelerated", "drafted", "publicized"],
     "'By the very officials charged with carrying them out' signals an ironic reversal, so the reforms were blocked."),
]

# (difficulty, first_sentence, second_sentence, correct, [distractors], rationale)
TRANSITIONS = [
    ("easy", "The museum offers free entry on the first Sunday of each month.",
     "visitors should expect long queues on those days.",
     "Consequently,", ["Nevertheless,", "For example,", "Previously,"],
     "Free entry causes the crowds, so the transition must signal result."),
    ("easy", "Emperor penguins breed during the Antarctic winter.",
     "they endure temperatures that would kill most other birds.",
     "As a result,", ["In contrast,", "For instance,", "Meanwhile,"],
     "Breeding in winter causes the exposure described, so a result transition is needed."),
    ("easy", "Aluminium is abundant in the earth's crust.",
     "it was once more valuable than gold, because separating it was so difficult.",
     "Nevertheless,", ["Therefore,", "Similarly,", "Afterward,"],
     "Abundance and high value are in tension, so the transition must mark contrast."),
    ("easy", "The soil in the valley retains water well.",
     "farmers there grow crops that would fail on the neighbouring slopes.",
     "Accordingly,", ["However,", "In contrast,", "Beforehand,"],
     "The soil property causes the farming outcome, so the transition signals result."),
    ("easy", "The orchestra rehearsed the passage for three weeks.",
     "the recording was completed in a single take.",
     "Ultimately,", ["Similarly,", "For example,", "Likewise,"],
     "The long rehearsal leads to the final outcome; 'Ultimately' marks that conclusion."),
    ("easy", "Sea ice reflects most of the sunlight that strikes it.",
     "open water absorbs it.",
     "By contrast,", ["Consequently,", "In addition,", "Afterward,"],
     "Reflecting and absorbing are opposed behaviours, so contrast is required."),
    ("medium", "Early telescopes suffered from severe colour fringing.",
     "Newton's reflecting design avoided the problem by using a mirror instead of a lens.",
     "In response,", ["Similarly,", "Regardless,", "Beforehand,"],
     "The new design answers the stated problem, so the transition marks a response to it."),
    ("medium", "The survey found broad public support for the measure.",
     "turnout at the referendum was among the lowest on record.",
     "Even so,", ["Therefore,", "Likewise,", "In particular,"],
     "Support and low turnout are in tension, calling for a concessive contrast."),
    ("medium", "Bamboo reaches full height in a single growing season.",
     "it is harvested on a far shorter cycle than hardwood timber.",
     "For this reason,", ["Nonetheless,", "In contrast,", "Previously,"],
     "Fast growth causes the short harvest cycle, so a causal transition fits."),
    ("medium", "The first draft of the constitution ran to ninety pages.",
     "the ratified text fits on four.",
     "In the end,", ["Similarly,", "Consequently,", "Furthermore,"],
     "The contrast between draft and final length is resolved chronologically by 'In the end'."),
    ("medium", "Most antibiotics target features unique to bacterial cells.",
     "they leave human cells largely unharmed.",
     "As a consequence,", ["Even so,", "In contrast,", "Beforehand,"],
     "The targeting explains the safety, so the transition signals result."),
    ("medium", "Restoring the fresco required matching pigments no longer manufactured.",
     "the conservators ground their own from mineral samples.",
     "Accordingly,", ["Nevertheless,", "In contrast,", "Similarly,"],
     "Grinding their own pigments is the response to the stated difficulty."),
    ("medium", "The company projected that the new plant would open in March.",
     "construction was still unfinished the following December.",
     "In fact,", ["Likewise,", "Therefore,", "For instance,"],
     "The outcome contradicts the projection, which 'In fact' introduces."),
    ("hard", "Standard accounts credit the printing press with the rapid spread of vernacular literature.",
     "manuscripts in vernacular languages circulated widely for a century beforehand.",
     "In fact,", ["Consequently,", "Similarly,", "As a result,"],
     "The second sentence corrects the standard account rather than following from it."),
    ("hard", "The alloy resists corrosion and weighs a third less than steel.",
     "its cost has confined it to aerospace applications.",
     "Still,", ["Thus,", "Indeed,", "Likewise,"],
     "Advantages are followed by a limitation that overrides them, so a concessive contrast is needed."),
    ("hard", "The model reproduced the observed migration routes almost exactly.",
     "it failed to predict the timing of departure, which its authors attribute to omitted weather variables.",
     "That said,", ["Accordingly,", "In turn,", "By comparison,"],
     "A success followed by an acknowledged shortcoming calls for a concessive qualification."),
    ("hard", "Excavations at the site have recovered thousands of animal bones but almost no cooking hearths.",
     "the assemblage may represent butchery carried out for consumption elsewhere.",
     "Taken together,", ["Conversely,", "Beforehand,", "Nonetheless,"],
     "The inference draws on both observations at once, which 'Taken together' signals."),
    ("hard", "Critics charged that the new tax would drive small firms out of the district.",
     "registrations of new businesses rose in each of the three following years.",
     "In the event,", ["Therefore,", "Similarly,", "In addition,"],
     "The outcome contradicts the prediction; 'In the event' introduces what actually happened."),
    ("hard", "Neural networks and human learners both improve with practice on a task.",
     "the resemblance breaks down under distribution shift, where humans generalize and networks often do not.",
     "Beyond that point,", ["Consequently,", "Likewise,", "For example,"],
     "The second sentence limits the analogy just drawn, marking where it stops holding."),
    ("easy", "Glass recycling saves substantial energy compared with making glass from raw sand.",
     "many municipalities have made glass collection a priority.",
     "For that reason,", ["Even so,", "In contrast,", "Earlier,"],
     "The energy saving causes the policy priority, so a causal transition fits."),
    ("easy", "The lighthouse was automated in 1987.",
     "no keeper has lived on the island since.",
     "Consequently,", ["Nevertheless,", "Similarly,", "For example,"],
     "Automation caused the end of resident keepers."),
    ("easy", "Camels can drink over a hundred litres of water in a few minutes.",
     "they can go for days without drinking at all.",
     "Conversely,", ["Therefore,", "In addition,", "Afterward,"],
     "Drinking enormous amounts and needing none are opposed behaviours, calling for contrast."),
    ("easy", "The festival was scheduled for the town square.",
     "heavy rain forced organizers to move it indoors.",
     "However,", ["Accordingly,", "Likewise,", "In particular,"],
     "The plan and what happened conflict, so contrast is required."),
    ("easy", "Sourdough relies on wild yeast already present in flour and air.",
     "it requires no commercial yeast at all.",
     "As a result,", ["Nonetheless,", "By contrast,", "Previously,"],
     "Relying on wild yeast causes the absence of commercial yeast."),
    ("easy", "The archive holds letters, ledgers, and photographs.",
     "it maintains a collection of architectural drawings.",
     "In addition,", ["Instead,", "However,", "Consequently,"],
     "The second item extends the list rather than replacing or opposing it."),
    ("medium", "The vaccine trial recruited participants across eleven countries.",
     "its results are more readily generalized than those of single-site studies.",
     "Accordingly,", ["Nevertheless,", "In contrast,", "Beforehand,"],
     "Broad recruitment causes the improved generalizability."),
    ("medium", "Engineers assumed the crack had formed under load.",
     "metallurgical analysis showed it predated the bridge's assembly.",
     "In fact,", ["Similarly,", "Therefore,", "Furthermore,"],
     "The analysis corrects the assumption, which 'In fact' introduces."),
    ("medium", "Digitizing the collection made it searchable from anywhere.",
     "it drew scholars away from the reading room, whose staff had answered questions no catalogue anticipates.",
     "At the same time,", ["Consequently,", "For instance,", "In short,"],
     "A benefit and a simultaneous cost call for a transition marking concurrence rather than result."),
    ("medium", "Solar panel costs have fallen by roughly ninety percent since 2010.",
     "installation now represents the larger share of a typical project's budget.",
     "As a consequence,", ["Even so,", "In contrast,", "Previously,"],
     "Falling panel costs cause installation to dominate the remaining budget."),
    ("medium", "The manuscript's marginalia are written in at least three hands.",
     "the volume passed through several readers before reaching the library.",
     "Evidently,", ["Regardless,", "In contrast,", "For example,"],
     "Three hands supports an inference about the book's history, which 'Evidently' marks."),
    ("medium", "Field recordings captured the bird's song across six regions.",
     "the dialects proved distinct enough that researchers could identify a bird's origin by ear.",
     "Indeed,", ["Nevertheless,", "By contrast,", "Beforehand,"],
     "The second sentence strengthens and confirms the first rather than opposing it."),
    ("hard", "The company attributed the outage to an unforeseeable hardware fault.",
     "an internal review found that the same component had failed twice in the preceding year.",
     "In the event,", ["Accordingly,", "Similarly,", "Furthermore,"],
     "The review contradicts the company's account of what actually happened."),
    ("hard", "Both treatments reduced symptoms substantially in the first month.",
     "only one maintained its effect at the twelve-month follow-up.",
     "Over the longer term,", ["Consequently,", "Likewise,", "In brief,"],
     "The contrast is specifically temporal: agreement early, divergence later."),
    ("hard", "Critics have read the painting's unfinished corner as evidence of the artist's failing health.",
     "X-ray imaging reveals a completed passage beneath, deliberately scraped away.",
     "Yet,", ["Therefore,", "Likewise,", "In particular,"],
     "The imaging contradicts the critics' reading, so contrast is needed."),
    ("hard", "The statute defines the offence in unusually broad terms.",
     "prosecutors have charged it in fewer than a dozen cases in thirty years.",
     "Even so,", ["Accordingly,", "Similarly,", "As a result,"],
     "Broad definition would predict frequent charges; the rarity is a concession against that expectation."),
    ("hard", "Standard models treat soil carbon as a stable long-term store.",
     "warming appears to accelerate microbial respiration, releasing carbon that the models hold fixed.",
     "On closer examination,", ["Consequently,", "Similarly,", "For that reason,"],
     "The second sentence complicates the model on further inspection rather than following from it."),
]

# (difficulty, [notes], goal, correct, [distractors], rationale)
SYNTHESIS = [
    ("easy",
     ["The kakapo is a flightless parrot native to New Zealand.",
      "It is nocturnal.", "Adults can weigh up to 4 kilograms.",
      "Fewer than 250 individuals remain."],
     "emphasize the kakapo's conservation status",
     "Fewer than 250 kakapo remain, making the flightless New Zealand parrot one of the world's rarest birds.",
     ["The kakapo is a nocturnal parrot native to New Zealand.",
      "Adult kakapo can weigh up to 4 kilograms.",
      "The kakapo is flightless and nocturnal."],
     "Only the choice citing the remaining population addresses conservation status."),
    ("easy",
     ["The Rosetta Stone was found in 1799.",
      "It carries the same decree in three scripts.",
      "The scripts are hieroglyphic, Demotic, and Greek.",
      "Scholars used the Greek to decipher the hieroglyphs."],
     "explain how the stone made decipherment possible",
     "Because the stone repeats one decree in hieroglyphic, Demotic, and Greek, scholars could use the Greek to decipher the hieroglyphs.",
     ["The Rosetta Stone was found in 1799.",
      "The Rosetta Stone carries a decree in three scripts.",
      "The Rosetta Stone is written partly in Greek."],
     "Only the choice linking the known script to the unknown one explains decipherment."),
    ("easy",
     ["Honey does not spoil.", "Sealed jars have been found in ancient tombs.",
      "Its low water content inhibits bacteria.", "It is also highly acidic."],
     "explain why honey does not spoil",
     "Honey resists spoilage because its low water content and high acidity together inhibit bacteria.",
     ["Sealed jars of honey have been found in ancient tombs.",
      "Honey does not spoil, even after thousands of years.",
      "Honey is both acidic and low in water."],
     "The goal is causal, and only one choice names both properties as the reason."),
    ("medium",
     ["The Silk Road was not a single road.",
      "It was a network of overland and maritime routes.",
      "It operated from roughly 130 BCE to 1450 CE.",
      "It carried goods, technologies, religions, and disease."],
     "emphasize the breadth of what the routes transmitted",
     "Along its overland and maritime routes the Silk Road carried not only goods but technologies, religions, and disease.",
     ["The Silk Road operated from roughly 130 BCE to 1450 CE.",
      "The Silk Road was a network rather than a single road.",
      "The Silk Road included both overland and maritime routes."],
     "Only one choice lists the range of things transmitted rather than the network's shape or dates."),
    ("medium",
     ["Ada Lovelace worked with Charles Babbage in the 1840s.",
      "She wrote notes on his proposed Analytical Engine.",
      "Her notes include an algorithm for computing Bernoulli numbers.",
      "She also argued the machine could manipulate symbols, not just numbers."],
     "emphasize the conceptual leap in Lovelace's notes",
     "Lovelace argued that the Analytical Engine could manipulate symbols rather than merely calculate, anticipating uses beyond arithmetic.",
     ["Ada Lovelace worked with Charles Babbage in the 1840s.",
      "Lovelace's notes include an algorithm for Bernoulli numbers.",
      "Lovelace wrote extensive notes on the Analytical Engine."],
     "The conceptual leap is the claim about symbols; the algorithm and the collaboration are context."),
    ("medium",
     ["Mount Tambora erupted in 1815.",
      "It ejected roughly 100 cubic kilometres of material.",
      "Global temperatures fell by about 0.5°C the following year.",
      "1816 became known as the year without a summer."],
     "emphasize the eruption's global climatic effect",
     "Tambora's 1815 eruption lowered global temperatures by about 0.5°C, producing the year without a summer in 1816.",
     ["Mount Tambora erupted in 1815, ejecting about 100 cubic kilometres of material.",
      "Mount Tambora is a volcano that erupted in 1815.",
      "The year 1816 was unusually cold in many places."],
     "Only one choice ties the eruption to the measured global temperature effect."),
    ("medium",
     ["Coffee rust is a fungal disease of coffee plants.",
      "It first devastated plantations in Ceylon in the 1870s.",
      "Growers there replaced coffee with tea.",
      "Ceylon tea remains a major export today."],
     "emphasize the long-term economic consequence of the outbreak",
     "After coffee rust destroyed Ceylon's plantations in the 1870s, growers switched to tea, which remains a major export today.",
     ["Coffee rust is a fungal disease that attacks coffee plants.",
      "Coffee rust reached Ceylon in the 1870s.",
      "Ceylon growers replaced their coffee plants with tea."],
     "The long-term consequence requires connecting the outbreak to tea's continuing importance."),
    ("hard",
     ["The Antikythera mechanism dates to roughly the second century BCE.",
      "It contains at least 30 bronze gears.",
      "It modelled the motions of the sun and moon.",
      "No comparably geared device is known for the next thousand years.",
      "Historians have revised assumptions about ancient engineering."],
     "emphasize why the mechanism forced a reassessment of ancient technology",
     "Because no comparably geared device appears for a thousand years afterward, the mechanism has forced historians to revise what they assumed ancient engineering could achieve.",
     ["The Antikythera mechanism contains at least 30 bronze gears.",
      "The Antikythera mechanism modelled the motions of the sun and moon.",
      "The Antikythera mechanism dates to roughly the second century BCE."],
     "The reassessment follows from the thousand-year gap, which only one choice mentions."),
    ("hard",
     ["Nauru was once among the richest countries per capita.",
      "Its wealth came from phosphate deposits.",
      "The deposits were largely exhausted by the 1990s.",
      "Mining left about 80 percent of the island uninhabitable.",
      "The country now imports nearly all its food."],
     "emphasize the lasting cost of the island's phosphate economy",
     "Phosphate mining left roughly 80 percent of Nauru uninhabitable and the country dependent on imported food once the deposits ran out.",
     ["Nauru was once among the richest countries per capita.",
      "Nauru's wealth came from its phosphate deposits.",
      "Nauru's phosphate deposits were exhausted by the 1990s."],
     "The lasting cost is the ruined land and import dependence, not the former wealth or the timeline."),
    ("hard",
     ["Lake Nyos is a crater lake in Cameroon.",
      "Carbon dioxide seeps into its depths from magma below.",
      "In 1986 the lake released a large cloud of the gas.",
      "The cloud suffocated more than 1,700 people.",
      "Degassing pipes were installed beginning in 2001."],
     "emphasize the measure taken to prevent a recurrence",
     "Since 2001, degassing pipes have vented carbon dioxide from Lake Nyos to prevent another release like the one that killed more than 1,700 people in 1986.",
     ["Lake Nyos is a crater lake in Cameroon fed by volcanic gas.",
      "In 1986 Lake Nyos released a cloud of carbon dioxide.",
      "Carbon dioxide seeps into Lake Nyos from magma below."],
     "Only one choice describes the preventive measure rather than the hazard or the disaster."),
]


# (difficulty, domain, skill, passage, stem, correct, [distractors], rationale)
PASSAGES = [
    ("easy", "information_ideas", "Central Ideas and Details",
     "The pistol shrimp hunts without touching its prey. Snapping one oversized claw shut produces a bubble that collapses so violently it generates a shock wave, stunning small fish at a distance of several centimetres.",
     "Which choice best states the main idea of the text?",
     "The pistol shrimp stuns prey at a distance using a shock wave produced by its claw.",
     ["The pistol shrimp has one claw larger than the other.",
      "The pistol shrimp is among the loudest animals in the ocean.",
      "Small fish are the pistol shrimp's only prey."],
     "The text describes the claw, the collapsing bubble, and the resulting shock wave that stuns prey at a distance."),
    ("easy", "information_ideas", "Central Ideas and Details",
     "Venice was built on soft mud, which cannot bear the weight of stone. Its builders drove millions of wooden piles into the seabed until they reached firmer clay beneath. Submerged in oxygen-poor water, the wood never rotted, and much of it still holds the city up.",
     "Which choice best states the main idea of the text?",
     "Venice stands on wooden piles that have survived because they sit in oxygen-poor water.",
     ["Venice was built on ground too soft to support any structure.",
      "Wooden piles are stronger than stone foundations.",
      "Venice's builders preferred wood to stone for aesthetic reasons."],
     "The text explains the soft ground, the piles driven to firmer clay, and why the wood survived."),
    ("easy", "information_ideas", "Central Ideas and Details",
     "Naked mole rats live in underground colonies with a single breeding female, an arrangement otherwise seen in insects rather than mammals. Workers dig tunnels with their teeth, and the colony can extend for kilometres beneath the soil.",
     "Which choice best states the main idea of the text?",
     "Naked mole rats live in colonies organized in a way rarely found among mammals.",
     ["Naked mole rats dig tunnels using their teeth.",
      "Naked mole rat colonies extend for kilometres.",
      "Insects and mammals often share social structures."],
     "The text's emphasis is the insect-like social structure, unusual for a mammal; the digging and extent are supporting details."),
    ("easy", "information_ideas", "Inferences",
     "Desert plants face a dilemma: the pores they open to take in carbon dioxide also release water. Many cacti open theirs only after dark, storing the gas until daylight allows photosynthesis to proceed.",
     "Which choice most logically completes the text?",
     "Opening the pores at night therefore reduces the water a cactus loses.",
     ["Cacti therefore photosynthesize more efficiently at night.",
      "Cacti therefore do not require carbon dioxide.",
      "Desert plants therefore keep their pores permanently closed."],
     "Water loss through open pores is the stated cost, and darkness is cooler, so night opening limits that loss."),
    ("easy", "information_ideas", "Inferences",
     "Tree rings grow wider in years with ample rainfall and narrower in dry ones. A timber beam salvaged from a ruined farmhouse shows a run of unusually narrow rings near its outer edge.",
     "Which choice most logically completes the text?",
     "The final years of the tree's growth were most likely unusually dry.",
     ["The tree was most likely cut down before it matured.",
      "The farmhouse was most likely built during a wet period.",
      "The beam most likely came from a species that grows slowly."],
     "Narrow rings indicate dry years, and rings near the outer edge are the most recent growth."),
    ("easy", "information_ideas", "Command of Evidence (Textual)",
     "A student claims that street trees measurably reduce summer temperatures in city neighbourhoods.",
     "Which finding, if true, would most directly support the student's claim?",
     "Sensors recorded afternoon temperatures three degrees lower on tree-lined streets than on comparable treeless streets nearby.",
     ["Street trees in the city are most commonly planted in spring.",
      "Residents report that tree-lined streets are more attractive.",
      "Street trees require regular pruning to remain healthy."],
     "The claim is about measured temperature reduction, and only the sensor comparison measures it."),
    ("medium", "information_ideas", "Central Ideas and Details",
     "Historians once treated the Library of Alexandria's destruction as a single catastrophic fire. Surviving records suggest something slower: shrinking budgets, the expulsion of scholars, and centuries of neglect, with fire only one episode among many. The library did not burn down so much as wind down.",
     "Which choice best states the main idea of the text?",
     "The library's loss was a gradual decline rather than one destructive event.",
     ["The library was never actually destroyed by fire.",
      "The library's scholars were responsible for its decline.",
      "Records of the library's history are largely unreliable."],
     "The text contrasts the single-fire account with budgets, expulsions, and neglect, concluding it 'wound down'."),
    ("medium", "information_ideas", "Central Ideas and Details",
     "The Voynich manuscript has resisted every attempt at translation since its rediscovery in 1912. Statistical analyses show its symbol frequencies behave like those of a natural language rather than random noise, yet no proposed decipherment has been reproducible. The text is either an unknown script or an unusually sophisticated hoax.",
     "Which choice best states the main idea of the text?",
     "The manuscript's linguistic statistics rule out randomness but have not settled whether it encodes a real language.",
     ["The manuscript is almost certainly an elaborate hoax.",
      "The manuscript was written in a language now extinct.",
      "Statistical analysis has produced a reproducible decipherment."],
     "The text reports language-like statistics, no reproducible decipherment, and two remaining possibilities."),
    ("medium", "information_ideas", "Inferences",
     "Migratory songbirds navigate partly by the stars. Birds raised in planetariums under an artificial sky oriented themselves toward whatever direction that sky designated as north, even when it conflicted with the earth's magnetic field.",
     "Which choice most logically completes the text?",
     "For these birds, celestial cues can override magnetic ones.",
     ["These birds cannot detect magnetic fields at all.",
      "Birds raised indoors lose the ability to navigate.",
      "Artificial skies disorient birds entirely."],
     "The birds followed the artificial sky even when it conflicted with the magnetic field, so the celestial cue took precedence."),
    ("medium", "information_ideas", "Inferences",
     "A pottery workshop's output can often be traced by the clay it used. Vessels excavated at an inland fortress match, in mineral composition, clay beds found only on a coastal plain two hundred kilometres away. No kiln has been found at the fortress.",
     "Which choice most logically completes the text?",
     "The vessels were most likely made on the coastal plain and transported inland.",
     ["The fortress most likely imported clay and fired it on site.",
      "The mineral analysis is most likely mistaken.",
      "The coastal plain was most likely settled from the fortress."],
     "Coastal clay plus no kiln at the fortress points to manufacture at the source and transport of finished vessels."),
    ("medium", "information_ideas", "Command of Evidence (Textual)",
     "Musicologist Farah Nasser argues that the sudden popularity of the twelve-string guitar in the 1960s owed less to its sound than to its visibility: a handful of televised performances put the instrument in front of millions.",
     "Which finding, if true, would most strongly support Nasser's argument?",
     "Sales of twelve-string guitars rose sharply in the weeks immediately following each televised performance, with no change in their price or design.",
     ["Twelve-string guitars produce a fuller sound than six-string models.",
      "Several prominent musicians preferred twelve-string guitars.",
      "Twelve-string guitars were more difficult to tune than six-string models."],
     "Nasser attributes popularity to visibility, so evidence must tie sales to the broadcasts rather than to the instrument's qualities."),
    ("medium", "information_ideas", "Command of Evidence (Quantitative)",
     "A city compared recycling rates before and after switching to fortnightly collection.\n\n| District | Before | After |\n|---|---|---|\n| Ashgrove | 41% | 52% |\n| Bellhaven | 38% | 47% |\n| Cranwell | 45% | 44% |\n| Dunmore | 36% | 49% |\n\nAn official concluded that the change raised recycling in most districts.",
     "Which choice best uses data from the table to support the official's conclusion?",
     "Rates rose in three of the four districts, by between 9 and 13 percentage points.",
     ["Cranwell's rate fell slightly, from 45% to 44%.",
      "Ashgrove had the highest rate after the change, at 52%.",
      "Dunmore had the lowest rate before the change, at 36%."],
     "The conclusion concerns increases across most districts, so the evidence must report their number and size."),
    ("hard", "information_ideas", "Central Ideas and Details",
     "Accounts of the Irish famine often centre on the potato blight. Economic historian Declan Mulready does not dispute the pathogen's role but notes that Ireland continued exporting grain, butter, and livestock throughout the worst years. The catastrophe, on his account, lay less in what the land failed to produce than in where its produce went.",
     "Which choice best states the main idea of the text?",
     "Mulready locates the famine's severity in the distribution of Irish food rather than in crop failure alone.",
     ["Mulready denies that the potato blight affected Ireland.",
      "Mulready argues that Ireland produced more food than it needed.",
      "Mulready believes the famine has been exaggerated by historians."],
     "Mulready accepts the blight but stresses continued exports, concluding the issue was where produce went."),
    ("hard", "information_ideas", "Inferences",
     "Radiocarbon dating assumes a known atmospheric ratio of carbon isotopes. Fossil fuel burning releases carbon so old that it contains no radiocarbon at all, diluting the atmospheric proportion measurably since the nineteenth century.",
     "Which choice most logically completes the text?",
     "Organic material formed recently may therefore appear older than it is when dated by this method without correction.",
     ["Radiocarbon dating is therefore unusable for any modern sample.",
      "Fossil fuels therefore contain more radiocarbon than living tissue.",
      "The atmospheric ratio has therefore remained constant since the nineteenth century."],
     "Dilution lowers the radiocarbon proportion, and a lower proportion reads as greater age unless corrected."),
    ("hard", "information_ideas", "Inferences",
     "A drug performed well in trials conducted at high-altitude clinics but showed no benefit at sea level. The compound's proposed mechanism depends on binding to haemoglobin, and residents at altitude carry substantially more haemoglobin than sea-level populations.",
     "Which choice most logically completes the text?",
     "The drug's apparent effectiveness may depend on the elevated haemoglobin levels found at altitude rather than on altitude itself.",
     ["The drug is therefore ineffective under all conditions.",
      "Altitude therefore causes the condition the drug treats.",
      "Haemoglobin levels therefore have no bearing on the drug's action."],
     "The mechanism runs through haemoglobin, which is elevated at altitude, so the binding target rather than elevation explains the pattern."),
    ("hard", "information_ideas", "Command of Evidence (Textual)",
     "Archaeologist Sunil Rao proposes that a settlement's unusual grain-storage pits were communal rather than household property. Critics note that communal and household storage can look identical once abandoned.",
     "Which finding, if true, would most weaken the critics' objection?",
     "The pits are clustered in a single open area at the settlement's centre, away from every identified dwelling.",
     ["The pits were all dug to approximately the same depth.",
      "Grain residue in the pits comes from several different crops.",
      "The pits remained in use for several generations."],
     "Placement away from dwellings and grouped centrally distinguishes communal from household storage, which is exactly what the critics say cannot be told apart."),
    ("hard", "information_ideas", "Command of Evidence (Quantitative)",
     "Researchers measured seedling survival under four canopy conditions after one year.\n\n| Canopy cover | Survival |\n|---|---|\n| 0% (open) | 22% |\n| 25% | 58% |\n| 50% | 71% |\n| 90% | 34% |\n\nThey concluded that seedlings of this species survive best under partial rather than full or absent canopy.",
     "Which choice best uses data from the table to support the researchers' conclusion?",
     "Survival peaked at 71% under 50% cover, exceeding both the open plots at 22% and the densest canopy at 34%.",
     ["Survival under 25% cover was 58%.",
      "Survival was lowest in the open plots, at 22%.",
      "Survival declined between 50% and 90% cover."],
     "The conclusion is that the middle of the range is best, so the evidence must compare the peak against both extremes."),
    ("easy", "craft_structure", "Text Structure and Purpose",
     "Most spiders build a fresh web each day. The bolas spider does not build one at all. It dangles a single silk line tipped with a sticky globule and swings it at passing moths, which it attracts by mimicking their scent.",
     "Which choice best states the main purpose of the text?",
     "To describe a hunting method that departs from typical spider behaviour",
     ["To explain how spiders produce silk",
      "To argue that bolas spiders are more efficient hunters than other spiders",
      "To compare the diets of different spider species"],
     "The text sets up the usual pattern, marks the bolas spider as an exception, and details that exception."),
    ("easy", "craft_structure", "Text Structure and Purpose",
     "The metric system was designed to be reproducible from nature: the metre was defined as a fraction of the earth's meridian. That definition proved impractical to check, and the metre is now fixed by the distance light travels in a specified fraction of a second.",
     "Which choice best describes the overall structure of the text?",
     "It presents an original definition and then explains what replaced it and why.",
     ["It argues that the metric system should be abandoned.",
      "It compares the metric system with older measurement systems.",
      "It describes how the earth's meridian was first measured."],
     "The text gives the original meridian-based definition, notes it was impractical, and states the current one."),
    ("medium", "craft_structure", "Text Structure and Purpose",
     "Conventional wisdom holds that adding lanes relieves traffic congestion. Transport data repeatedly show otherwise: within a few years, new capacity fills with trips that were not previously made at all. Engineers call the effect induced demand, and it means a wider road often carries more vehicles at the same crawling speed.",
     "Which choice best states the main purpose of the text?",
     "To present evidence that contradicts a common assumption and name the mechanism behind it",
     ["To recommend a specific transport policy for cities",
      "To describe how traffic engineers measure congestion",
      "To compare road widening with public transport investment"],
     "The text states the assumption, gives contrary data, and names induced demand as the mechanism."),
    ("medium", "craft_structure", "Text Structure and Purpose",
     "The following is adapted from a novel. The narrator has returned to a house she left as a child.\n\nThe banister was exactly where my hand expected it, which was worse than if it had been moved. Everything had been kept. Nothing had been kept for me.",
     "Which choice best describes the function of the final two sentences?",
     "They draw a distinction between preservation and welcome that unsettles the narrator.",
     ["They explain why the narrator originally left the house.",
      "They describe the physical condition of the house in detail.",
      "They indicate that the house has new occupants."],
     "'Everything had been kept. Nothing had been kept for me.' separates the house's preservation from any claim on the narrator."),
    ("hard", "craft_structure", "Text Structure and Purpose",
     "Ecologists have long treated invasive species as uniformly damaging. Botanist Ingrid Sorensen resists the framing without denying the harm. On degraded land where native seed banks are exhausted, she argues, fast-colonizing non-natives can stabilize soil and shade out bare ground, creating conditions under which natives can later be reintroduced. The label describes an origin, not an effect.",
     "Which choice best describes the function of the final sentence in the text?",
     "It states the conceptual point the preceding example was offered to establish.",
     ["It concedes a limitation in Sorensen's argument.",
      "It introduces a new line of evidence about seed banks.",
      "It restates the conventional ecological position."],
     "'The label describes an origin, not an effect' generalizes from the degraded-land case into the claim the passage is making."),
    ("hard", "craft_structure", "Text Structure and Purpose",
     "Translators of ancient poetry face a problem archaeologists do not. A broken pot can be displayed with its gaps visible, its incompleteness part of what the viewer sees. A translation cannot show its own fractures without ceasing to read as a poem, so the losses it incurs are precisely the ones its reader will never know about.",
     "Which choice best states the main purpose of the text?",
     "To explain why the losses in a translation are harder to perceive than those in a physical artifact",
     ["To argue that ancient poetry should not be translated",
      "To describe the methods archaeologists use to restore pottery",
      "To compare the training of translators and archaeologists"],
     "The pot's visible gaps are contrasted with a translation whose fractures cannot show, making its losses invisible to readers."),

    ("easy", "information_ideas", "Central Ideas and Details",
     "Octopuses have no bones, and can squeeze through any opening larger than their beak, the single rigid part of their body. Aquarium keepers size lids not by the animal's bulk but by that one measurement.",
     "Which choice best states the main idea of the text?",
     "An octopus's beak, not its overall size, determines the gaps it can pass through.",
     ["Octopuses frequently escape from aquariums.",
      "Octopuses are the most flexible animals in the ocean.",
      "Aquarium keepers prefer lids made of rigid material."],
     "The text identifies the beak as the limiting rigid part and notes keepers size lids by it."),
    ("easy", "information_ideas", "Central Ideas and Details",
     "The Mary Rose sank in 1545 and lay under silt for four centuries. The silt sealed out oxygen, so the timbers and even the crew's woollen caps survived. When the hull was raised in 1982 it brought up an inventory of Tudor daily life that no document records.",
     "Which choice best states the main idea of the text?",
     "Oxygen-free silt preserved objects that written sources never described.",
     ["The Mary Rose was the largest warship of its era.",
      "Tudor documents contain detailed inventories of shipboard life.",
      "Raising the hull in 1982 damaged much of the cargo."],
     "The passage attributes preservation to the oxygen-free silt and stresses that the finds are undocumented elsewhere."),
    ("easy", "information_ideas", "Inferences",
     "Antarctic ice cores trap air bubbles at the moment the snow compacts. Bubbles from layers dated to the 1950s contain measurably less carbon dioxide than bubbles from layers dated to the 2000s.",
     "Which choice most logically completes the text?",
     "Atmospheric carbon dioxide therefore rose between those two periods.",
     ["Ice cores therefore cannot preserve air reliably.",
      "Snow therefore compacts more slowly than it once did.",
      "Antarctic temperatures therefore fell over the same period."],
     "The bubbles sample the atmosphere at the time of trapping, so a rise across layers indicates a rise in the atmosphere."),
    ("easy", "information_ideas", "Inferences",
     "A café owner tracked sales after moving the pastry case from beside the door to beside the register. Pastry sales rose by a third; nothing else about the menu, staffing, or pricing changed that month.",
     "Which choice most logically completes the text?",
     "The case's position beside the register most likely contributed to the increase.",
     ["Customers most likely began preferring pastries to coffee.",
      "The café most likely lowered its pastry prices.",
      "The increase was most likely caused by a change in staffing."],
     "The position was the one thing that changed, so it is the available explanation; the text rules the others out."),
    ("easy", "information_ideas", "Command of Evidence (Textual)",
     "A researcher claims that providing free public transit passes increases the number of trips people take to medical appointments.",
     "Which finding, if true, would most directly support the researcher's claim?",
     "Clinics in districts where passes were distributed recorded a rise in kept appointments, while clinics in districts without passes recorded no change.",
     ["Public transit ridership rose overall in the year the passes were introduced.",
      "Most pass recipients reported being satisfied with the programme.",
      "The passes were valid on buses but not on the commuter rail line."],
     "The claim links passes to medical trips specifically, and only the clinic comparison isolates that effect against a control."),
    ("medium", "information_ideas", "Central Ideas and Details",
     "Standard histories of vaccination begin with Edward Jenner in 1796. Variolation, deliberate exposure to a mild smallpox strain, was practised in China and the Ottoman Empire generations earlier and reached Britain through Lady Mary Wortley Montagu's advocacy in the 1720s. Jenner's contribution was safer method, not first principle.",
     "Which choice best states the main idea of the text?",
     "Deliberate immunization predates Jenner, whose advance was in safety rather than in the underlying idea.",
     ["Jenner's work in 1796 has been shown to be fraudulent.",
      "Variolation was more effective than vaccination.",
      "Lady Mary Wortley Montagu invented the practice of variolation."],
     "The text places variolation earlier and characterizes Jenner's role as a safer method, not the original insight."),
    ("medium", "information_ideas", "Central Ideas and Details",
     "The Dust Bowl is often explained by drought alone. Soil scientist Halima Osei points out that droughts of comparable severity struck the same counties in the 1890s without stripping the topsoil. What differed by the 1930s was the depth and extent of mechanized ploughing, which had broken the deep-rooted grass that held the soil in place.",
     "Which choice best states the main idea of the text?",
     "Osei attributes the Dust Bowl's severity to ploughing practices rather than to drought by itself.",
     ["Osei argues that the 1930s drought was more severe than earlier ones.",
      "Osei believes mechanized ploughing increased crop yields.",
      "Osei denies that drought occurred in the 1930s."],
     "The 1890s comparison isolates ploughing, not drought, as the differing factor."),
    ("medium", "information_ideas", "Inferences",
     "Some moths have evolved ears tuned to the frequencies bats use for echolocation. On islands that bats never colonized, related moth species have the same ear structures but show no behavioural response when those frequencies are played.",
     "Which choice most logically completes the text?",
     "The hearing structures appear to persist without the evasive behaviour once the predator is absent.",
     ["Bats therefore never used echolocation on those islands.",
      "The island moths therefore cannot hear at all.",
      "Ears therefore evolve only in the presence of predators."],
     "The islands preserve the structures but lose the response, so anatomy outlasts the behaviour when the pressure is gone."),
    ("medium", "information_ideas", "Inferences",
     "A publisher found that novels with the author's name in larger type sold better, and concluded that type size drives sales. The publisher had reserved the largest type for its already best-selling authors.",
     "Which choice most logically completes the text?",
     "The correlation is therefore better explained by the authors' existing popularity than by the typography.",
     ["Type size therefore has a stronger effect than the publisher realized.",
      "Best-selling authors therefore prefer smaller type.",
      "The publisher therefore should reduce type size on all covers."],
     "Large type was assigned to authors who already sold well, so prior popularity confounds the comparison."),
    ("medium", "information_ideas", "Command of Evidence (Quantitative)",
     "Researchers recorded nesting success for a bird species at four distances from a road.\n\n| Distance from road | Nests fledging young |\n|---|---|\n| 50 m | 31% |\n| 200 m | 54% |\n| 500 m | 68% |\n| 1000 m | 70% |\n\nThey concluded that road proximity depresses nesting success, with the effect levelling off beyond a few hundred metres.",
     "Which choice best uses data from the table to support the researchers' conclusion?",
     "Success climbed steeply from 31% at 50 m to 68% at 500 m, then changed little between 500 m and 1000 m.",
     ["Nests 1000 m from the road fledged young 70% of the time.",
      "Nests closest to the road were least successful, at 31%.",
      "Success at 200 m was 54%, higher than at 50 m."],
     "The conclusion has two parts, a decline near roads and a plateau further out, and only one choice reports both."),
    ("medium", "information_ideas", "Command of Evidence (Textual)",
     "Historian Priya Raghunathan argues that the spread of coffeehouses in seventeenth-century London mattered less for the drink than for the reading: each house subscribed to newspapers that individuals could not afford alone.",
     "Which finding, if true, would most strongly support Raghunathan's argument?",
     "Surviving coffeehouse accounts show newspaper subscriptions as a larger recurring expense than coffee beans.",
     ["Coffee consumption in London rose sharply after 1650.",
      "Coffeehouses were concentrated near the Royal Exchange.",
      "Several coffeehouses employed their own roasters."],
     "Raghunathan's claim ranks reading above the drink, and the expense comparison tests exactly that ranking."),
    ("hard", "information_ideas", "Central Ideas and Details",
     "Economists have long modelled traffic fatalities as falling with vehicle safety features. Policy analyst Bram de Vries notes that pedestrian deaths in several countries rose over the same decades in which occupant deaths fell, and that the vehicles credited with protecting occupants grew heavier and taller. Safety, on his account, was redistributed rather than created.",
     "Which choice best states the main idea of the text?",
     "De Vries argues that gains in occupant safety came partly at pedestrians' expense rather than representing a net reduction in harm.",
     ["De Vries denies that vehicle safety features protect occupants.",
      "De Vries argues that pedestrian deaths are undercounted.",
      "De Vries believes heavier vehicles are safer for everyone."],
     "Falling occupant deaths alongside rising pedestrian deaths supports the 'redistributed rather than created' conclusion."),
    ("hard", "information_ideas", "Inferences",
     "Lead isotope ratios differ measurably between ore fields. Bronze artefacts from a Mediterranean shipwreck carry ratios matching a single Anatolian source, while the tin in the same objects matches deposits in Cornwall, some four thousand kilometres away.",
     "Which choice most logically completes the text?",
     "The objects therefore combine metals drawn from opposite ends of a long-distance exchange network.",
     ["The isotope analysis is therefore unreliable for tin.",
      "The artefacts were therefore manufactured in Cornwall.",
      "Anatolian and Cornish ores therefore share a common origin."],
     "Copper from Anatolia and tin from Cornwall in one object implies materials travelling across a wide network."),
    ("hard", "information_ideas", "Inferences",
     "A machine-learning model trained to detect pneumonia from chest X-rays performed excellently on its training hospital's images and poorly elsewhere. Investigators found the model had learned to read a small metal token that one hospital's technicians clipped to the film of patients admitted through the emergency department.",
     "Which choice most logically completes the text?",
     "The model's apparent skill rested on a marker correlated with illness rather than on features of the lungs themselves.",
     ["The model therefore requires higher-resolution images to work.",
      "Pneumonia therefore cannot be detected from chest X-rays.",
      "The training hospital therefore had unusually accurate radiologists."],
     "Reading the token rather than the anatomy explains both the strong in-hospital result and the failure elsewhere."),
    ("hard", "information_ideas", "Command of Evidence (Textual)",
     "Musicologist Tobias Lindgren claims a set of anonymous eighteenth-century sonatas was written by a single composer. Sceptics reply that the shared features Lindgren cites were common to the entire regional school.",
     "Which finding, if true, would most weaken the sceptics' objection?",
     "The sonatas share an unusual fingering notation that appears in no other surviving manuscript from the region.",
     ["The sonatas were all copied onto paper from the same mill.",
      "The sonatas use the same three-movement structure as others of the period.",
      "The sonatas were catalogued together in a nineteenth-century library."],
     "A feature absent from every other regional manuscript cannot be explained as a shared regional convention, which is the sceptics' whole objection."),
    ("hard", "information_ideas", "Command of Evidence (Quantitative)",
     "A trial compared two tutoring formats over one term.\n\n| Format | Mean gain | Students below baseline |\n|---|---|---|\n| One-to-one | 14.2 points | 3% |\n| Small group | 13.8 points | 4% |\n| Large group | 9.1 points | 17% |\n| No tutoring | 4.6 points | 22% |\n\nResearchers concluded that small-group tutoring delivers nearly the benefit of one-to-one at a fraction of the staffing cost.",
     "Which choice best uses data from the table to support the researchers' conclusion?",
     "Small-group students gained 13.8 points against 14.2 for one-to-one, a difference of well under half a point.",
     ["One-to-one tutoring produced the largest mean gain, at 14.2 points.",
      "Students receiving no tutoring gained only 4.6 points.",
      "Large-group tutoring left 17% of students below baseline."],
     "The claim is that small-group nearly matches one-to-one, so the evidence must be the near-equality of those two figures."),
    ("medium", "craft_structure", "Words in Context",
     "The witness's testimony was ______ on the central point: he had given three different times for the same event.",
     "Which choice completes the text with the most logical and precise word or phrase?",
     "inconsistent",
     ["emphatic", "rehearsed", "inaudible"],
     "Three different times for one event is self-contradiction, which 'inconsistent' names."),
    ("hard", "craft_structure", "Words in Context",
     "The building's facade is ______ of the period, but its steel frame belongs to a technology the period's architects had not yet trusted.",
     "Which choice completes the text with the most logical and precise word or phrase?",
     "characteristic",
     ["independent", "dismissive", "unaware"],
     "'But' contrasts a typical exterior with an atypical structure, so the facade must be representative of its era."),
    ("medium", "craft_structure", "Text Structure and Purpose",
     "Peer review is often described as a filter that keeps error out of the literature. It works better as a filter on presentation: reviewers see a manuscript, not a laboratory, and can judge whether an argument follows from the data shown without being able to verify that the data were collected as described.",
     "Which choice best states the main purpose of the text?",
     "To refine a common description of what peer review can and cannot check",
     ["To argue that peer review should be abolished",
      "To describe the history of the peer review system",
      "To compare peer review across scientific disciplines"],
     "The text replaces 'filter on error' with 'filter on presentation' and explains the limit reviewers work under."),
    ("hard", "craft_structure", "Text Structure and Purpose",
     "Restorers of historic buildings distinguish between repair and reconstruction, and the distinction is not merely technical. A repaired wall carries its own history in the mismatch of old stone and new mortar. A reconstructed wall presents a past that never had a present: it looks as the building is supposed to have looked on a day nobody witnessed.",
     "Which choice best describes the function of the final sentence in the text?",
     "It sharpens the distinction just drawn by characterizing what reconstruction actually produces.",
     ["It concedes that reconstruction is sometimes necessary.",
      "It introduces the technical methods used in reconstruction.",
      "It restates the definition of repair given earlier."],
     "The closing sentence defines reconstruction as presenting an unwitnessed past, making the repair/reconstruction contrast pointed."),
]


def build(rng):
    out = []

    for difficulty, domain, skill, passage, stem, correct, distractors, why in PASSAGES:
        options = [correct] + list(distractors)
        rng.shuffle(options)
        ids = "ABCD"
        out.append({
            "section": "reading_writing", "domain": domain, "skill": skill,
            "difficulty": difficulty, "question_type": "multiple_choice",
            "stimulus": passage, "stem": stem,
            "choices": [{"id": ids[i], "text": v} for i, v in enumerate(options)],
            "correct_answer": ids[options.index(correct)],
            "rationale": why, "source": "self_authored",
        })

    for difficulty, sentence, correct, distractors, why in WORDS_IN_CONTEXT:
        options = [correct] + list(distractors)
        rng.shuffle(options)
        ids = "ABCD"
        out.append({
            "section": "reading_writing", "domain": "craft_structure",
            "skill": "Words in Context", "difficulty": difficulty,
            "question_type": "multiple_choice", "stimulus": sentence,
            "stem": WIC_STEM,
            "choices": [{"id": ids[i], "text": v} for i, v in enumerate(options)],
            "correct_answer": ids[options.index(correct)],
            "rationale": why, "source": "self_authored",
        })

    for difficulty, first, second, correct, distractors, why in TRANSITIONS:
        options = [correct] + list(distractors)
        rng.shuffle(options)
        ids = "ABCD"
        out.append({
            "section": "reading_writing", "domain": "expression_of_ideas",
            "skill": "Transitions", "difficulty": difficulty,
            "question_type": "multiple_choice",
            "stimulus": f"{first} ______ {second}",
            "stem": TRANS_STEM,
            "choices": [{"id": ids[i], "text": v} for i, v in enumerate(options)],
            "correct_answer": ids[options.index(correct)],
            "rationale": why, "source": "self_authored",
        })

    for difficulty, notes, goal, correct, distractors, why in SYNTHESIS:
        options = [correct] + list(distractors)
        rng.shuffle(options)
        ids = "ABCD"
        bullets = "\n".join(f"- {n}" for n in notes)
        out.append({
            "section": "reading_writing", "domain": "expression_of_ideas",
            "skill": "Rhetorical Synthesis", "difficulty": difficulty,
            "question_type": "multiple_choice",
            "stimulus": f"While researching a topic, a student took the following notes:\n\n{bullets}",
            "stem": f"The student wants to {goal}. Which choice most effectively uses "
                    f"relevant information from the notes to accomplish this goal?",
            "choices": [{"id": ids[i], "text": v} for i, v in enumerate(options)],
            "correct_answer": ids[options.index(correct)],
            "rationale": why, "source": "self_authored",
        })

    rng.shuffle(out)
    return out


def main():
    p = argparse.ArgumentParser(description="Expand authored R&W corpora.")
    p.add_argument("--seed", type=int, default=23)
    p.add_argument("--out", required=True)
    args = p.parse_args()

    questions = build(random.Random(args.seed))
    with open(args.out, "w", encoding="utf-8") as f:
        json.dump({
            "_note": "Expanded by scripts/generate_rw_content.py from authored "
                     "corpora. Original items.",
            "questions": questions,
        }, f, indent=2, ensure_ascii=False)

    counts = {}
    for q in questions:
        counts[(q["domain"], q["difficulty"])] = counts.get((q["domain"], q["difficulty"]), 0) + 1
    print(f"wrote {len(questions)} questions to {args.out}")
    for k, v in sorted(counts.items()):
        print(f"  {k[0]:24} {k[1]:7} {v}")


if __name__ == "__main__":
    main()
